# Generated by Django 5.1.4 on 2024-12-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_country_description_alter_country_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="economicdata",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="economicdata",
            name="gdp_growth_lag1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="economicdata",
            name="interest_rate_lag1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="economicdata",
            name="unemployment_lag1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="economicdata",
            name="cpi",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="economicdata",
            name="gdp_growth",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="economicdata",
            name="unemployment_rate",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
